# Generated by Django 4.2.16 on 2024-11-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sec_id', models.AutoField(primary_key=True, serialize=False)),
                ('sec_name', models.CharField(max_length=100)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('subsection_id', models.AutoField(primary_key=True, serialize=False)),
                ('subsection_name', models.CharField(max_length=100)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
                ('sec_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.section')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('pan', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('education', models.CharField(max_length=50)),
                ('dep_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
                ('grade_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.grade')),
                ('sec_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.section')),
                ('subsection_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.subsection')),
            ],
        ),
    ]
