# Generated by Django 4.2.16 on 2024-11-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plant_id',
            field=models.IntegerField(default=1004),
        ),
    ]
